### ISSUE TITLE
Publish on homebrew

### ISSUE THREAD

**Issue by TimAufdemKampe** [bendews/apw#2]
If i run `brew install apw` i get this error:

```
Warning: No available formula with the name "apw". Did you mean apt or apr?
==> Searching for similarly named formulae and casks...
==> Formulae
apr

To install apr, run:
  brew install apr

==> Casks
scap-workbench

To install scap-workbench, run:
  brew install --cask scap-workbench
```

**Comment by bendews** [comment]
Thanks so much for your interest in my project! I had expected MacOS 15 and the new Passwords.app to completely break this tool so I hadn't actually put the effort in to getting it into homebrew core as of yet. I have been running 10.15 for a few weeks now and it actually seems to work really well with it, so on my todo list :) As an alternative until I have added it to homebrew you can download the latest version from the releases page.

**Comment by bendews** [comment]
I've prepared v1.0.0 via #4 as a pre-req to publishing on brew, hopefully all goes well and it will be there soon. 😄

**Comment by bendews** [comment]
@TimAufdemKampe unfortunately this project does not meet the minimum popularity for inclusion in `homebrew-core` however I have added instructions on installing from my own tap (just run `brew install bendews/homebrew-tap/apw`). I will close this issue for now - feel free to share the project around so we can get it included in `homebrew-core` 😄  Thanks so much!
