### ISSUE TITLE
Add build instructions?

### ISSUE THREAD

**Issue by 5HT2** [bendews/apw#3]
It would be great if we could build this package ourselves, & be able to contribute, while waiting for #2 to be resolved.

I'd be happy to fix #1 if you could share what's needed to actually build a new binary, and I can add documentation to the readme myself in a separate pull request.

Thanks for writing this! Every other solution I found for interacting with `authd` either is broken, or does not do what I need it to do, or is frustrating to use.

**Comment by bendews** [comment]
Added instructions with #4 👍
